---
# see https://github.com/nextapps-de/flexsearch/tree/0.6.32#tokenizer for options
tokenizer: "forward" # strict, forward, reverse, full
searchableAttributes:
  - "prefLabel"
  - "altLabel"
  - "hiddenLabel"
  - "definition"
  - "example"
fail_on_validation: false
ui:
  colors:
    skoHubWhite: "rgb(255, 255, 255)"
    skoHubDarkColor: "rgb(0, 47, 98)"
    skoHubMiddleColor: "rgb(0, 47, 98)"
    skoHubLightColor: "rgb(40, 200, 175)"
    skoHubThinColor: "rgb(55, 250, 210)"
    skoHubBlackColor: "rgb(5, 30, 30)"
    skoHubAction: "rgb(230, 0, 125)"
    skoHubNotice: "rgb(250, 180, 50)"
    skoHubDarkGrey: "rgb(155, 155, 155)"
    skoHubMiddleGrey: "rgb(200, 200, 200)"
    skoHubLightGrey: "rgb(235, 235, 235)"
  logo: "mvp.png" # Path
  title: "Vocabs of unterrichtsvideos.net"
  fonts:
    regular:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 400
      name: "ubuntu-v20-latin-regular"
    bold:
      font_family: "Ubuntu"
      font_style: "normal"
      font_weight: 700
      name: "ubuntu-v20-latin-700"
